output_dir: ./ # Not needed

# Model arguments
model:
  _component_: torchtune.models.llama2.llama2_7b

representation_type: cartesian
conditional: False

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /storage/ice-shared/vip-vxp/Shared/llm4mat-ft-weights/llama2-epoch7/
  checkpoint_files: [
    model-00001-of-00002.safetensors,
    model-00002-of-00002.safetensors,
  ]
  output_dir: ${output_dir}
  model_type: LLAMA2

device: cuda
dtype: bf16

seed: 

# Tokenizer arguments
tokenizer:
  _component_: torchtune.models.llama2.llama2_tokenizer
  path: /storage/ice-shared/vip-vxp/Shared/llm4mat-ft-weights/llama2-epoch7/tokenizer.model
  max_seq_len: null
  prompt_template: null

# Generation arguments; defaults taken from gpt-fast
prompt:
  system: null
  user: null
max_new_tokens: 300
temperature: 0.6 # 0.8 and 0.6 are popular values to try
top_k: 300

enable_kv_cache: True

quantizer: null